"""
This type stub file was generated by pyright.
"""

class Context:
    """A context."""
    def __init__(self, name, orchestrator=..., host=..., endpoints=..., tls=...) -> None:
        ...
    
    def set_endpoint(self, name=..., host=..., tls_cfg=..., skip_tls_verify=..., def_namespace=...): # -> None:
        ...
    
    def inspect(self): # -> dict[str, Unknown]:
        ...
    
    @classmethod
    def load_context(cls, name): # -> Self@Context | None:
        ...
    
    def save(self): # -> None:
        ...
    
    def remove(self): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __call__(self): # -> dict[str, Unknown]:
        ...
    
    def is_docker_host(self): # -> bool:
        ...
    
    @property
    def Name(self): # -> Unknown:
        ...
    
    @property
    def Host(self): # -> None:
        ...
    
    @property
    def Orchestrator(self): # -> None:
        ...
    
    @property
    def Metadata(self): # -> dict[str, Unknown]:
        ...
    
    @property
    def TLSConfig(self): # -> None:
        ...
    
    @property
    def TLSMaterial(self): # -> dict[str, dict[Unknown, Unknown]]:
        ...
    
    @property
    def Storage(self): # -> dict[str, dict[str, str]]:
        ...
    


