"""
This type stub file was generated by pyright.
"""

class TLSConfig:
    """
    TLS configuration.

    Args:
        client_cert (tuple of str): Path to client cert, path to client key.
        ca_cert (str): Path to CA cert file.
        verify (bool or str): This can be a bool or a path to a CA cert
            file to verify against. If ``True``, verify using ca_cert;
            if ``False`` or not specified, do not verify.
        ssl_version (int): A valid `SSL version`_.
        assert_hostname (bool): Verify the hostname of the server.

    .. _`SSL version`:
        https://docs.python.org/3.5/library/ssl.html#ssl.PROTOCOL_TLSv1
    """
    cert = ...
    ca_cert = ...
    verify = ...
    ssl_version = ...
    def __init__(self, client_cert=..., ca_cert=..., verify=..., ssl_version=..., assert_hostname=..., assert_fingerprint=...) -> None:
        ...
    
    def configure_client(self, client): # -> None:
        """
        Configure a client with these TLS options.
        """
        ...
    


