---
version: "2"

services:
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data
  runner-manager:
    build: .
    ports:
      - 8000:8000
    environment:
      REDIS_OM_URL: redis://redis:6379
    command: uvicorn runner_manager.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./runner_manager:/app/runner_manager
    x-develop:
      watch:
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: docker-compose.yaml
  worker:
    build: .
    command: rq worker -c runner_manager.jobs.settings
    volumes:
      - .:/app
    environment:
      REDIS_OM_URL: redis://redis:6379
  github-mock:
    profiles:
      - develop
    build: tests/images/github-mock
    ports:
      - 4010:4010
    x-develop:
      watch:
        - action: rebuild
          path: tests/images/github-mock

volumes:
  redis_data:
    driver: local
