---
services:
  redis:
    profiles:
      - tests
      - dev
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data
  runner-manager:
    profiles:
      - dev
    depends_on:
      - redis
    build: .
    user: root
    ports:
      - 8000:8000
    environment:
      GITHUB_TOKEN: ${RUNNER_MANAGER_TOKEN}
      REDIS_OM_URL: redis://redis:6379
      CONFIG_FILE: /app/config.yaml
    command: uvicorn runner_manager.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./runner_manager:/app/runner_manager
      - ./config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  webhook:
    profiles:
      - dev
    build: tests/images/webhook
    environment:
      URL: http://runner-manager:8000/webhook
      REPO: ${REPO}
      GITHUB_TOKEN: ${RUNNER_MANAGER_TOKEN}
  worker:
    profiles:
      - dev
    depends_on:
      - redis
    build: .
    command: rq worker --with-scheduler -c runner_manager.jobs.settings
    # Required when connecting to docker daemon from inside the container
    user: root
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REDIS_OM_URL: redis://redis:6379
      CONFIG_FILE: /app/config.yaml
      GITHUB_TOKEN: ${RUNNER_MANAGER_TOKEN}
  github-mock:
    profiles:
      - tests
    build: tests/images/github-mock
    ports:
      - 4010:4010
volumes:
  redis_data:
    driver: local
