---
version: "2"

services:
  redis:
    profiles:
      - main
      - develop
      - tests
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data
  runner-manager:
    profiles:
      - main
      - develop
    build: .
    ports:
      - 8000:8000
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_BASE_URL: http://github-mock:4010
      REDIS_OM_URL: redis://redis:6379
      CONFIG_FILE: /app/config.yaml
    command: uvicorn runner_manager.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./runner_manager:/app/runner_manager
      - ./config.yaml:/app/config.yaml
  worker:
    profiles:
      - main
      - develop
    build: .
    command: rq worker --with-scheduler -c runner_manager.jobs.settings
    volumes:
      - .:/app
    environment:
      REDIS_OM_URL: redis://redis:6379
      CONFIG_FILE: /app/config.yaml
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_BASE_URL: http://github-mock:4010

  github-mock:
    profiles:
      - develop
      - tests
    build: tests/images/github-mock
    ports:
      - 4010:4010
volumes:
  redis_data:
    driver: local
