"""
This type stub file was generated by pyright.
"""

from vmware.vapi.bindings.struct import VapiStruct

"""
Error classes and factory
"""
__author__ = ...
__copyright__ = ...

class VapiError(VapiStruct, Exception):
    """
    Representation of VMODL Error in python language bindings
    """

    def __init__(self, error_value=...) -> None:
        """
        Initialize VapiError

        :type  error_value: :class:`vmware.vapi.data.value.ErrorValue` or
            :class:`None`
        :param error_value: ErrorValue to be used for VapiError
        """
        ...

    def get_error_value(self):  # -> StructValue:
        """
        Returns the corresponding ErrorValue for the VapiError class

        :rtype: :class:`vmware.vapi.data.value.ErrorValue`
        :return: ErrorValue for this VapiError
        """
        ...

class UnresolvedError(VapiError):
    """
    VapiError which represents a VMODL2 error that was reported but couldn't
    be resolved
    """

    ...
