"""
This type stub file was generated by pyright.
"""

"""
Rest http helper methods
"""
__author__ = ...
__copyright__ = ...
logger = ...

class ResponseExtractor:
    """
    Http response extractor utility classes
    """

    def __init__(self) -> None:
        """
        Initialize the response extractor
        """
        ...

    def set_http_status(self, status):  # -> None:
        """
        Set http response status

        :type  status: :class:`str`
        :param status: Http status
        """
        ...

    def get_http_status(self):  # -> None:
        """
        Get http response status

        :rtype: :class:`str`
        :return: Http response status
        """
        ...

    def set_http_headers(self, headers):  # -> None:
        """
        Set http response headers

        :type  headers: :class:`dict` of :class:`str`, :class:`str`
        :param headers: Http response headers
        """
        ...

    def get_http_headers(self):  # -> None:
        """
        Get http response headers

        :rtype: :class:`dict` of :class:`str`, :class:`str`
        :return: Http response headers
        """
        ...

    def set_http_body(self, body):  # -> None:
        """
        Set http response body

        :type  body: :class:`str`
        :param body: Http body object
        """
        ...

    def get_http_body(self):  # -> None:
        """
        Get http response body

        :rtype: :class:`str`
        :return: Http response body
        """
        ...

    def set_http_method(self, method):  # -> None:
        """
        Set http request method

        :type  method: :class:`vmware.vapi.protocol.common.http_lib.HttpMethod`
        :param method: Http request method
        """
        ...

    def get_http_method(self):  # -> None:
        """
        Get http request method

        :rtype: :class:`vmware.vapi.protocol.common.http_lib.HttpMethod`
        :return: Http request method
        """
        ...

    def set_http_url(self, url):  # -> None:
        """
        Set http request URL

        :type  url: :str`
        :param url: Http request url
        """
        ...

    def get_http_url(self):  # -> None:
        """
        Get http request url

        :rtype: :class:`str`
        :return: Http request url
        """
        ...
