"""
This type stub file was generated by pyright.
"""

"""
Utility library for validating IRI that conform to RFC 3987
"""
__author__ = ...
__copyright__ = ...
logger = ...
class URIValidator:
    """
    Helper class for validation of IRI's
    """
    _rules = ...
    compiled_regex = ...
    @staticmethod
    def validate(iri): # -> None:
        """
        Validate the given IRI string

        :type  iri: :class:`str`
        :param iri: IRI string to be validated
        """
        ...
    


