"""
This type stub file was generated by pyright.
"""

"""
Protocol connector factory
"""
__author__ = ...
__copyright__ = ...
logger = ...

class ProtocolConnectorFactory:
    """Protocol connector factory"""

    def __init__(self) -> None:
        """Protocol connector factory init"""
        ...

    def get_connector(self, protocol, *args, **kwargs):  # -> Any | None:
        """
        Create protocol connector

        :type    protocol: :class:`str`
        :param   protocol: protocol name
        :type    args: :class:`tuple`
        :param   args: position parameters to protocol connector constructor
        :type    kwargs: :class:`dict`
        :param   kwargs: key parameters to protocol connector constructor
        :rtype:  :class:`vmware.vapi.protocol.client.connector.Connector`
        :return: Connector object
        """
        ...
