"""
This type stub file was generated by pyright.
"""

"""
Helper module to build value passed in UserAgent header
"""
__author__ = ...
__copyright__ = ...

class UserAgentBuilder:
    """Builder for the value to be passed in UserAgent header"""

    VSHPERE_SDK_DIST_NAME = ...
    def __init__(self) -> None: ...
    def build(self):  # -> str:
        ...

    def load_sdk_version(self):  # -> None:
        ...

    def set_product_info(
        self, name, version, product_comment=..., vapi_version=...
    ):  # -> None:
        ...

_user_agent_builder = ...

def init_product_info(name, version, product_comment=..., vapi_version=...):  # -> None:
    """
    Initializes details of the application layer that need to be passed
    as part of the user agent header

    Example:
    calling init_product_info('DCLI', 2.10.0, product_comment='i', vapi_version=2.9.1)
    would produced User-Agent header:
    DCLI/2.10.0 (i) vAPI/2.9.1 Python/2.7.13+ (Linux; 4.13.0-45-generic; x86_64)

    :type  name: :class:`str`
    :param name: Service identifier
    :type  version: :class:`str`
    :param version: Operation identifier
    :type  product_comment: :class:`str`
    :param product_comment: Adds additional comment to the name and version data
    :type  vapi_version: :class:`str`
    :param vapi_version: Specifies vapi version to use explicitly
    """
    ...

def get_user_agent():  # -> str:
    """
    Gets the string that needs to be passed in the UserAgent header

    :rtype: :class:`str`
    :return: UserAgent value
    """
    ...
