"""
This type stub file was generated by pyright.
"""

from vmware.vapi.message import MessageFormatter

"""
Helper classes for formatting the message for localization
"""
__author__ = ...
__copyright__ = ...

class StringFormatter(MessageFormatter):
    """
    Format the string
    """

    string_template = ...
    format_specifier = ...
    @classmethod
    def format_msg(cls, msg, args):  # -> LiteralString:
        """
        Format the string

        :type  msg: :class:`str`
        :param msg: Message template
        :type  args: :class:`list` of :class:`object`
        :param args: Arguments for the message
        :rtype: :class:`str`
        :return: Localized message
        """
        ...
