{{- if .Values.deployment.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "runner-manager.fullname" . }}
  labels:
    {{- include "runner-manager.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.deployment.ingress.basicAuthCreds }}
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- end}}
    {{- range $key, $value := .Values.deployment.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.deployment.ingress.fqdn }}
    http:
      paths:
        - path: {{ .Values.deployment.ingress.path | quote }}
          backend:
            serviceName: {{ include "runner-manager.fullname" . }}
            servicePort: {{ $.Values.deployment.service.port }}
  {{- if .Values.deployment.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.deployment.ingress.fqdn }}
    secretName: {{ .Values.deployment.ingress.tlsSecret }}
  {{- end }}
{{- end }}
