"""
This type stub file was generated by pyright.
"""

"""
Convenience methods for dynamic loading
"""
__author__ = ...
__copyright__ = ...
logger = ...
def dynamic_import(constructor): # -> Any | None:
    """
    Dynamically import a module and get the specified module attribute

    :type    constructor: :class:`str`
    :param   constructor: Fully qualified module attribute
    :rtype:  :class:`object`
    :return: Python object
    """
    ...

def dynamic_import_list(constructors): # -> list[Any | None]:
    """
    Dynamically import a list of modules

    :type    constructors: :class:`list` of :class:`str`
    :param   constructors: List of fully qualified module attributes
    :rtype:  :class:`list` of :class:`object`
    :return: List of imported python objects
    """
    ...

