"""
This type stub file was generated by pyright.
"""

import logging

"""
Helper functions for configuring logging in vapi runtime
"""
__author__ = ...
__copyright__ = ...
NO_OP_ID_MSG = ...

def get_raw_request_logger():  # -> Logger:
    """
    Return the raw request logger that is not propagated to root logger and
    disabled by default.
    :rtype: :class:`logging.Logger`
    :return: Raw request logger
    """
    ...

def get_client_wire_logger():  # -> Logger:
    """
    Return the client wire logger that is not propagated to root logger and
    disabled by default. It is used to log raw wire request/responses
    :rtype: :class:`logging.Logger`
    :return: Raw request logger
    """
    ...

def get_provider_wire_logger():  # -> Logger:
    """
    Return the provider wire logger that is not propagated to root logger and
    disabled by default. It is used to log raw wire request/responses
    :rtype: :class:`logging.Logger`
    :return: Raw request logger
    """
    ...

class VapiFilter(logging.Filter):
    """
    This is a filter that injects operation id into the log record
    """

    def filter(self, record):  # -> Literal[True]:
        ...

_vapi_filter = ...

def get_vapi_logger(logger_name):  # -> Logger:
    """
    Return a logger that is compatible with the VAPI provider log formats.
    Currently, it only adds the VapiFilter

    :rtype: :class:`logging.Logger`
    :return: Vapi provider logger
    """
    ...

PROVIDER_WIRE_LOGGER_NAME = ...
CLIENT_WIRE_LOGGER_NAME = ...
_client_wire_logger = ...
_provider_wire_logger = ...
