"""
This type stub file was generated by pyright.
"""

import socket
import urllib3
import urllib3.connection
from docker.transport.basehttpadapter import BaseHTTPAdapter

RecentlyUsedContainer = urllib3._collections.RecentlyUsedContainer
class SSHSocket(socket.socket):
    def __init__(self, host) -> None:
        ...
    
    def connect(self, **kwargs): # -> None:
        ...
    
    def sendall(self, data): # -> None:
        ...
    
    def send(self, data): # -> int:
        ...
    
    def recv(self, n): # -> bytes:
        ...
    
    def makefile(self, mode): # -> IO[bytes] | None:
        ...
    
    def close(self): # -> None:
        ...
    


class SSHConnection(urllib3.connection.HTTPConnection):
    def __init__(self, ssh_transport=..., timeout=..., host=...) -> None:
        ...
    
    def connect(self): # -> None:
        ...
    


class SSHConnectionPool(urllib3.connectionpool.HTTPConnectionPool):
    scheme = ...
    def __init__(self, ssh_client=..., timeout=..., maxsize=..., host=...) -> None:
        ...
    


class SSHHTTPAdapter(BaseHTTPAdapter):
    __attrs__ = ...
    def __init__(self, base_url, timeout=..., pool_connections=..., max_pool_size=..., shell_out=...) -> None:
        ...
    
    def get_connection(self, url, proxies=...): # -> SSHConnectionPool:
        ...
    
    def close(self): # -> None:
        ...
    


