"""
This type stub file was generated by pyright.
"""

"""
Utility library for Provider modules
"""
__author__ = ...
__copyright__ = ...

def augment_method_result_with_errors(
    service_id, operation_id, method_result, errors_to_augment
):  # -> MethodResult:
    """
    Returns a new method result that is identical to `method_result` except that
    the `errors_definition` field in the `output` (which is of type
    Operation.Info from Introspection service) contains the errors from the Info
    structure in `method_result` plus the errors in `errors_to_augment`. This
    code will be executed only for "get" operation in vAPI Operation
    Introspection service.

    :type  service_id: :class:`str`
    :param service_id: Service identifier
    :type  operation_id: :class:`str`
    :param operation_id: Operation identifier
    :type  method_result: :class:`vmware.vapi.core.MethodResult`
    :param method_result: Operation result
    :type  errors_to_augment: :class:`list` of
        :class:`vmware.vapi.data.value.StructValue`
    :param errors_to_augment: Errors to augment. These are struct values of type
        com.vmware.vapi.std.introspection.Operation.DataDefinition whose `type`
        field has the value ERROR
        to the DataDefinition type in Introspection service IDL.
    :rtype: :class:`vmware.vapi.data.value.DataValue`
    :return: Output data value
    """
    ...

def augment_method_def_with_errors(method_def, errors):  # -> MethodDefinition:
    """
    Add errors reported by this ApiProviderFilter to a method definition.
    This method clones the input method definition and appends errors. It
    does not modify the parameter.

    :type  method_def: :class:`vmware.vapi.core.MethodDefinition`
    :param method_def: Method definition
    :type  errors: :class:`list` of
        :class:`vmware.vapi.data.definition.ErrorDefinition`
    :param errors: Error definitions to augment to MethodDefinition
    :rtype: :class:`vmware.vapi.core.MethodDefinition`
    :return: Method definition after augmenting the errors
    """
    ...
