"""
This type stub file was generated by pyright.
"""

from functools import lru_cache

@lru_cache(maxsize=None)
def check_for_command(conn, cmd): # -> bool:
    ...

@lru_cache(maxsize=None)
def has_redis_json(conn=...): # -> bool:
    ...

@lru_cache(maxsize=None)
def has_redisearch(conn=...): # -> bool:
    ...

