"""
This type stub file was generated by pyright.
"""

"""
Task Helper for clients
"""
__author__ = ...
__copyright__ = ...
class Task:
    """
    Task Helper class for clients
    """
    def __init__(self, task_id, task_svc_instance, result_type) -> None:
        """
        Initialize the Task Helper class

        :type  task_id: :class:`str`
        :param task_id: Task Id
        :type  task_svc_instance: :class:`com.vmware.cis_client.Tasks`
        :param task_svc_instance: Task Service instance
        :type  result_type: :class:`vmware.vapi.bindings.BindingType`
        :param result_type: Result type
        """
        ...
    
    def get_task_id(self): # -> Any:
        """
        Returns task id

        :rtype: :class:`str`
        :return: Task Id
        """
        ...
    
    def get_info(self):
        """
        Returns tasks info

        :rtype: :class:`com.vmware.cis.tasks_client.Info`
        :return: Task Info
        """
        ...
    
    def get_result(self): # -> str | Any | StructValue | list[Any] | set[Any] | VapiStruct | UnresolvedError | datetime | Enum | dict[Any, Any] | None:
        """
        Returns task result

        :rtype: :class:`com.vmware.cis.tasks_client.Info`
        :return: Task Result
        """
        ...
    
    def get_error(self):
        """
        Returns task error

        :rtype: :class:`Exception`
        :return: Task Error
        """
        ...
    


