"""
This type stub file was generated by pyright.
"""

"""
Convenient libraries for introspection data
"""
__author__ = ...
__copyright__ = ...
logger = ...
data_type_map = ...
reverse_data_type_map = ...

def convert_data_def_to_data_value(data_def):  # -> StructValue:
    """
    Convert :class:`vmware.vapi.data.definition.DataDefinition` object to
    :class:`vmware.vapi.data.value.DataValue` object. The type of the object
    returned is a struct value that corresponds to DataDefinition VMODL2 type
    present in introspection service.

    :type  data_def: :class:`vmware.vapi.data.definition.DataDefinition`
    :param data_def: Data definition
    :rtype: :class:`vmware.vapi.data.value.DataValue`
    :return: Data value representing the data definition object
    """
    ...

def convert_data_value_to_data_def(data_value):
    """
    Convert :class:`vmware.vapi.data.value.DataValue` object that
    corresponds to DataDefinition structure in introspection VMODL2 into
    :class:`vmware.vapi.data.definition.DataDefinition` object.

    :type  data_value: :class:`vmware.vapi.data.value.DataValue`
    :param data_value: Data value representing the data definition object
    :rtype: :class:`vmware.vapi.data.definition.DataDefinition`
    :return: Data definition
    """
    ...
