"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional
from ... import redis

log = ...
class MigrationError(Exception):
    ...


def import_submodules(root_module_name: str): # -> None:
    """Import all submodules of a module, recursively."""
    ...

def schema_hash_key(index_name): # -> str:
    ...

def create_index(conn: redis.Redis, index_name, schema, current_hash): # -> None:
    ...

class MigrationAction(Enum):
    CREATE = ...
    DROP = ...


@dataclass
class IndexMigration:
    model_name: str
    index_name: str
    schema: str
    hash: str
    action: MigrationAction
    conn: redis.Redis
    previous_hash: Optional[str] = ...
    def run(self): # -> None:
        ...
    
    def create(self): # -> None:
        ...
    
    def drop(self): # -> None:
        ...
    


class Migrator:
    def __init__(self, module=...) -> None:
        ...
    
    def detect_migrations(self): # -> None:
        ...
    
    def run(self): # -> None:
        ...
    


