"""
This type stub file was generated by pyright.
"""

from typing import Optional, Pattern

class TokenEscaper:
    """
    Escape punctuation within an input string.
    """
    DEFAULT_ESCAPED_CHARS = ...
    def __init__(self, escape_chars_re: Optional[Pattern] = ...) -> None:
        ...
    
    def escape(self, value: str) -> str:
        ...
    


