---
name: dependancy review

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dependency-review:
    needs: trivy-sbom
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3