---
name: deployment

on: pull_request

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helm/kind-action@v1
      - name: deploy kustomize
        run: kubectl apply -k manifests/
      - name: Check if deployment is ok
        run: |
          kubectl rollout status statefulset redis --timeout=90s
          kubectl rollout status deployment runner-manager --timeout=90s
      - name: Get resources status
        run: kubectl get all
        if: failure()
