---
name: Trunk Check

on: [pull_request]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - run: poetry install
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
